# Generated by Django 5.2.8 on 2025-11-25 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='Sold Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_classes', to='events.event')),
            ],
            options={
                'verbose_name': 'Ticket Class',
                'verbose_name_plural': 'Ticket Classes',
            },
        ),
    ]
