version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: nexusticket_db
    restart: always
    environment:
      MYSQL_DATABASE: events
      MYSQL_ROOT_PASSWORD: sina12345
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:alpine
    container_name: nexusticket_redis
    restart: always
    ports:
      - "6380:6379"

  web:
    build: .
    container_name: nexusticket_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build: .
    container_name: nexusticket_celery
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  mysql_data: