import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronDown, Heart, Minus, Plus, SlidersHorizontal, Sparkles, Star, Truck, X } from 'lucide-react'
import { useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { categories, productBySlug, products, type Category, type Product } from '../data/catalog'
import { useLanguage } from '../i18n/sinshop'
import { Link, useLocation, useNavigate, useParams, useSearchParams } from '../router'
import { route, ProductCard } from '../components/ShopUI'
import { useShop } from '../context/ShopContext'
import { filterProducts, type Sort } from '../lib/commerce'

const PageIntro = ({ kicker, title, children }: { kicker?: string; title: string; children?: ReactNode }) => <section className="page-intro"><div><span>{kicker}</span><h1>{title}</h1>{children}</div></section>
const categoryName = (category: Category) => categories.find(item => item.id === category)?.label ?? category

export const HomePage = () => {
  const { locale, t } = useLanguage(); const featured = products.filter(item => item.featured).slice(0, 4)
  return <main><section className="hero"><img src="https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1800&q=88" alt="Athlete moving at dusk" fetchPriority="high" /><div className="hero-shade" /><div className="hero-copy"><span>{t('heroKicker')}</span><h1>{t('hero')}</h1><p>{t('heroCopy')}</p><div><Link className="button" to={route(locale, '/shop')}>{t('shopCollection')} <ArrowUpRight size={18} /></Link><Link className="button button--ghost" to={route(locale, '/story')}>{t('discoverStory')}</Link></div></div><p className="hero-index">01 / 04 <ArrowDown size={17} /></p></section>
    <section className="section category-section"><div className="section-head"><div><span>{t('categoryKicker')}</span><h2>{t('categoryTitle')}</h2></div><Link to={route(locale, '/shop')}>{t('viewAll')} <ArrowUpRight /></Link></div><div className="category-grid">{categories.map((category, index) => <Link className="category-card" to={route(locale, `/categories/${category.id}`)} key={category.id}><img src={category.image} alt="" loading="lazy" /><div><small>0{index + 1}</small><h3>{category.label}</h3><p>{category.line}</p></div></Link>)}</div></section>
    <section className="section product-section"><div className="section-head"><div><span>{t('featuredKicker')}</span><h2>{t('featuredTitle')}</h2></div><Link to={route(locale, '/shop')}>{t('viewAll')} <ArrowUpRight /></Link></div><div className="product-grid">{featured.map(product => <ProductCard product={product} key={product.id} />)}</div></section>
    <section className="campaign"><div className="campaign-copy"><span>{t('campaignKicker')}</span><h2>{t('campaignTitle')}</h2><p>{t('campaignCopy')}</p><Link className="text-link" to={route(locale, '/categories/recovery')}>{t('exploreTechnology')} <ArrowUpRight size={17} /></Link></div><div className="campaign-image"><img src="https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&w=1200&q=85" alt="Athlete stretching after training" loading="lazy" /><p>DESIGNING FOR <strong>THE AFTER</strong></p></div></section>
    <section className="section values"><div className="section-head"><div><span>{t('valuesKicker')}</span><h2>{t('valuesTitle')}</h2></div></div><div className="value-grid">{[[t('responsible'), '01'], [t('tested'), '02'], [t('delivery'), '03'], [t('returns'), '04']].map(([label, number]) => <div key={String(number)}><small>{number}</small><h3>{label}</h3><ArrowUpRight /></div>)}</div></section>
    <section className="newsletter"><div><span>{t('newsletterKicker')}</span><h2>{t('newsletterTitle')}</h2></div><form onSubmit={event => event.preventDefault()}><input type="email" required placeholder={t('email')} aria-label={t('email')} /><button className="button" type="submit">{t('subscribe')} <ArrowUpRight size={17} /></button><p>{t('privacy')}</p></form></section>
  </main>
}

export const ShopPage = ({ category }: { category?: Category }) => {
  const { locale, t, money } = useLanguage(); const [params, setParams] = useSearchParams(); const [showFilters, setShowFilters] = useState(false); const query = params.get('search') ?? ''; const selected = params.get('category') ?? category ?? ''; const sort = params.get('sort') ?? 'featured'; const [maxPrice, setMaxPrice] = useState(400); const [inStock, setInStock] = useState(false)
  const filtered = useMemo(() => filterProducts(products, { category: selected, maxPrice, inStock, query, sort: sort as Sort }), [selected, maxPrice, inStock, query, sort])
  const set = (changes: Record<string, string>) => { const next = new URLSearchParams(params); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); setParams(next) }
  const reset = () => { setMaxPrice(400); setInStock(false); setParams(new URLSearchParams()) }
  return <main className="shop-page"><PageIntro kicker={category ? categoryName(category) : t('shop')} title={category ? `${categoryName(category)} / ${t('shop')}` : t('shop')}><p>{category ? categories.find(item => item.id === category)?.line : 'A considered collection for training, recovery and the life around both.'}</p></PageIntro><div className="shop-toolbar"><button className="filter-trigger" onClick={() => setShowFilters(true)}><SlidersHorizontal size={16} /> {t('filters')}</button><p>{filtered.length} {t('results')}</p><label>{t('sort')}<select value={sort} onChange={event => set({ sort: event.target.value })}><option value="featured">{t('featured')}</option><option value="new">{t('newest')}</option><option value="low">{t('low')}</option><option value="high">{t('high')}</option><option value="rated">{t('rated')}</option></select></label></div><div className="shop-layout"><FilterPanel open={showFilters} close={() => setShowFilters(false)} selected={selected} maxPrice={maxPrice} inStock={inStock} set={set} setMaxPrice={setMaxPrice} setInStock={setInStock} reset={reset} /><section className="product-grid product-grid--shop">{filtered.length ? filtered.map(product => <ProductCard product={product} key={product.id} />) : <div className="no-results"><h2>{t('noResults')}</h2><button className="button button--dark" onClick={reset}>{t('reset')}</button></div>}</section></div></main>
}

const FilterPanel = ({ open, close, selected, maxPrice, inStock, set, setMaxPrice, setInStock, reset }: { open: boolean; close: () => void; selected: string; maxPrice: number; inStock: boolean; set: (value: Record<string, string>) => void; setMaxPrice: (value: number) => void; setInStock: (value: boolean) => void; reset: () => void }) => { const { t, money } = useLanguage(); return <aside className={`filters ${open ? 'is-open' : ''}`} aria-label={t('filters')}><header><h2>{t('filters')}</h2><button onClick={close} aria-label={t('close')}><X /></button></header><button className="clear-filters" onClick={reset}>{t('clear')}</button><fieldset><legend>{t('categories')}</legend>{categories.map(category => <label key={category.id}><input type="radio" checked={selected === category.id} onChange={() => set({ category: category.id })} name="category" /> {category.label}</label>)}<label><input type="radio" checked={!selected} onChange={() => set({ category: '' })} name="category" /> All</label></fieldset><fieldset><legend>{t('priceRange')} <span>{money(maxPrice)}</span></legend><input type="range" min="19" max="400" step="10" value={maxPrice} onChange={event => setMaxPrice(Number(event.target.value))} /></fieldset><fieldset><legend>{t('availability')}</legend><label><input type="checkbox" checked={inStock} onChange={event => setInStock(event.target.checked)} /> {t('inStock')}</label></fieldset><button className="button button--dark mobile-filter-done" onClick={close}>{t('results')}</button></aside> }

export const ProductPage = () => {
  const { slug } = useParams<{ slug: string }>(); const product = productBySlug(slug); const { locale, t, money } = useLanguage(); const { add, wishlist, toggleWish } = useShop(); const [size, setSize] = useState(product?.sizes[0] ?? ''); const [color, setColor] = useState(product?.colors[0] ?? ''); const [quantity, setQuantity] = useState(1); const [section, setSection] = useState<'description' | 'features' | 'materials'>('description')
  if (!product) return <NotFound />
  const addMany = () => Array.from({ length: quantity }).forEach(() => add(product, size, color))
  return <main className="product-page"><div className="breadcrumb"><Link to={route(locale)}>{t('home')}</Link> / <Link to={route(locale, '/shop')}>{t('shop')}</Link> / {product.name}</div><div className="product-detail"><div className="gallery"><img src={product.image} alt={product.imageAlt} /><img src={product.image.replace('w=1000', 'w=900')} alt="" loading="lazy" /></div><section className="purchase"><p>{categoryName(product.category)}</p><div className="product-title-row"><h1>{product.name}</h1><button className={wishlist.includes(product.id) ? 'is-active' : ''} onClick={() => toggleWish(product.id)} aria-label={t('wishlist')}><Heart fill={wishlist.includes(product.id) ? 'currentColor' : 'none'} /></button></div><div className="rating"><Star size={14} fill="currentColor" /> {product.rating} <span>{product.reviews} {t('reviews')}</span></div><strong className="price">{money(product.price)}</strong><p className="product-description">{product.description}</p>{product.colors.length > 1 && <div className="selector"><span>{t('selectColor')}</span><div>{product.colors.map(item => <button key={item} className={color === item ? 'selected color-dot' : 'color-dot'} onClick={() => setColor(item)} style={{ background: item }} aria-label={item} />)}</div></div>}{product.sizes.length > 1 && <div className="selector"><span>{t('selectSize')}</span><div className="sizes">{product.sizes.map(item => <button className={size === item ? 'selected' : ''} key={item} onClick={() => setSize(item)}>{item}</button>)}</div></div>}<div className="purchase-actions"><div className="detail-quantity"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={15} /></button><span>{quantity}</span><button onClick={() => setQuantity(Math.min(product.stock, quantity + 1))}><Plus size={15} /></button></div><button className="button button--dark" onClick={addMany}>{t('add')} <ArrowUpRight size={17} /></button></div><Link className="button button--outline" to={route(locale, '/checkout')} onClick={addMany}>{t('buyNow')}</Link><p className="delivery"><Truck size={18} /> {t('deliveryInfo')}</p><div className="accordions">{(['description', 'features', 'materials'] as const).map(item => <div key={item}><button onClick={() => setSection(section === item ? 'description' : item)}>{t(item)} <ChevronDown /></button>{section === item && <p>{item === 'features' ? product.features.join(' · ') : item === 'materials' ? product.materials : product.description}</p>}</div>)}</div></section></div><section className="section related"><div className="section-head"><div><span>{t('featuredKicker')}</span><h2>{t('related')}</h2></div></div><div className="product-grid">{products.filter(item => item.category === product.category && item.id !== product.id).slice(0, 4).map(item => <ProductCard key={item.id} product={item} />)}</div></section></main>
}

export const WishlistPage = () => { const { wishlist } = useShop(); const { t } = useLanguage(); const saved = products.filter(product => wishlist.includes(product.id)); return <main className="section wishlist-page"><PageIntro title={t('wishlist')} /><div className="product-grid">{saved.length ? saved.map(product => <ProductCard key={product.id} product={product} />) : <div className="no-results"><h2>{t('emptyBag')}</h2></div>}</div></main> }

export const CheckoutPage = () => { const { cart, clearCart } = useShop(); const { locale, t, money } = useLanguage(); const navigate = useNavigate(); const [submitted, setSubmitted] = useState(false); const total = cart.reduce((sum, line) => sum + line.product.price * line.quantity, 0); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); clearCart(); window.scrollTo({ top: 0 }) }
  if (submitted) return <main className="confirmation"><Check /><span>{t('confirmation')}</span><h1>{t('confirmationCopy')}</h1><p>SS-2026-7K9M</p><Link className="button button--dark" to={route(locale, '/account')}>{t('account')}</Link></main>
  if (!cart.length) return <main className="confirmation"><ShoppingBagIcon /><h1>{t('emptyBag')}</h1><Link className="button button--dark" to={route(locale, '/shop')}>{t('continueShopping')}</Link></main>
  return <main className="checkout"><section><PageIntro title={t('checkoutTitle')} /><form onSubmit={submit}><CheckoutBlock title={t('contact')}><input required placeholder={t('email')} type="email" /></CheckoutBlock><CheckoutBlock title={t('shippingAddress')}><div className="form-grid"><input required placeholder={t('firstName')} /><input required placeholder={t('lastName')} /><input required placeholder={t('country')} /><input required placeholder={t('city')} /><input required placeholder={t('address')} /><input required placeholder={t('postal')} /></div></CheckoutBlock><CheckoutBlock title={t('payment')}><input required minLength={12} inputMode="numeric" placeholder={t('card')} /><label className="checkbox"><input required type="checkbox" /> {t('terms')}</label></CheckoutBlock><button className="button button--dark" type="submit">{t('placeOrder')} <ArrowUpRight size={17} /></button></form></section><aside className="checkout-summary"><h2>{t('bagTitle')}</h2>{cart.map(line => <p key={line.product.id}><span>{line.product.name} × {line.quantity}</span><strong>{money(line.product.price * line.quantity)}</strong></p>)}<p className="checkout-total"><span>{t('total')}</span><strong>{money(total)}</strong></p></aside></main> }
const CheckoutBlock = ({ title, children }: { title: string; children: ReactNode }) => <fieldset className="checkout-block"><legend>{title}</legend>{children}</fieldset>
const ShoppingBagIcon = () => <Sparkles size={40} />

export const AuthPage = ({ register = false }: { register?: boolean }) => { const { locale, t } = useLanguage(); const navigate = useNavigate(); const [error, setError] = useState(''); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (String(form.get('password')).length < 8) return setError(t('passwordHint')); localStorage.setItem('sinshop-session', 'demo'); navigate(route(locale, '/account')) }; return <main className="auth-page"><div className="auth-image"><img src="https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=85" alt="Training space" /><p>SINSHOP<br /><strong>MOVE WELL.</strong></p></div><section className="auth-form"><Link className="wordmark" to={route(locale)}>SIN<span>◒</span>SHOP</Link><span>{register ? t('create') : t('signIn')}</span><h1>{register ? t('register') : t('signIn')}</h1><form onSubmit={submit}>{register && <div className="form-grid"><input required name="firstName" placeholder={t('firstName')} /><input required name="lastName" placeholder={t('lastName')} /></div>}<input required name="email" type="email" placeholder={t('email')} /><input required name="password" type="password" placeholder={t('password')} autoComplete={register ? 'new-password' : 'current-password'} />{register && <input required minLength={8} type="password" placeholder={t('confirmPassword')} />}{!register && <label className="checkbox"><input type="checkbox" /> {t('remember')}</label>}{error && <p className="form-error">{error}</p>}<button className="button button--dark" type="submit">{register ? t('create') : t('signIn')} <ArrowUpRight size={17} /></button></form><p>{register ? t('haveAccount') : t('noAccount')} <Link to={route(locale, register ? '/login' : '/register')}>{register ? t('signIn') : t('register')}</Link></p><Link className="text-link" to={route(locale, '/forgot')}>{t('forgot')}</Link></section></main> }

export const AccountPage = () => { const { locale, t, setLocale } = useLanguage(); const navigate = useNavigate(); const signedIn = localStorage.getItem('sinshop-session'); if (!signedIn) return <AuthPage />; return <main className="section account-page"><PageIntro kicker="SINSHOP MEMBER" title={t('account')} /><div className="account-grid"><nav><button>{t('profile')}</button><button>{t('orders')}</button><Link to={route(locale, '/wishlist')}>{t('saved')}</Link><label>{t('settings')}<select value={locale} onChange={event => { const next = event.target.value as typeof locale; setLocale(next); navigate(route(next, '/account')) }}><option value="en">English</option><option value="fa">فارسی</option><option value="tr">Türkçe</option><option value="ru">Русский</option></select></label><button onClick={() => { localStorage.removeItem('sinshop-session'); navigate(route(locale)) }}>{t('signOut')}</button></nav><section><h2>Alex Morgan</h2><p>alex@sinshop.demo</p><div className="order-card"><span>SS-2026-7K9M</span><strong>$238</strong><p>Axis Knit Runner · Form Seamless Tee</p></div></section></div></main> }

export const StoryPage = () => { const { locale, t } = useLanguage(); return <main className="story"><PageIntro kicker="SINSHOP / 2026" title={t('storyTitle')}><p>{t('storyCopy')}</p></PageIntro><img src="https://images.unsplash.com/photo-1558611848-73f7eb4001a1?auto=format&fit=crop&w=1800&q=85" alt="Athlete and movement" /><section><span>01 / A LONGER VIEW</span><h2>Gear should honour the effort—not distract from it.</h2><p>We choose lasting materials, remove the unnecessary and stay close to the everyday rituals that make movement meaningful.</p><Link className="button button--dark" to={route(locale, '/shop')}>{t('shopCollection')}</Link></section></main> }

export const InfoPage = ({ kind }: { kind: 'contact' | 'shipping' | 'legal' | 'faq' }) => { const { t } = useLanguage(); const contact = kind === 'contact'; const title = kind === 'shipping' ? t('shippingReturns') : kind === 'legal' ? t('legal') : kind === 'faq' ? t('faq') : t('contactTitle'); return <main className="info-page"><PageIntro title={title}><p>{contact ? t('contactCopy') : kind === 'shipping' ? t('deliveryInfo') : 'We believe clear policies create a calmer shopping experience.'}</p></PageIntro>{contact ? <form className="contact-form" onSubmit={event => event.preventDefault()}><input placeholder={t('firstName')} required /><input type="email" placeholder={t('email')} required /><textarea placeholder={t('message')} required /><button className="button button--dark">{t('send')}</button></form> : <div className="info-copy"><h2>{kind === 'faq' ? 'Care, fit and delivery' : title}</h2><p>Every SinShop order is prepared with care. This portfolio version presents the product experience and does not process real payments or shipments.</p><p>For help with an order, our support team is available every day.</p></div>}</main> }
export const NotFound = () => { const { locale, t } = useLanguage(); return <main className="confirmation"><h1>{t('notFound')}</h1><Link className="button button--dark" to={route(locale)}>{t('backHome')}</Link></main> }
