# Generated by Django 5.2.7 on 2026-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_amount_coupon_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='total_capacity',
            field=models.PositiveIntegerField(default=100, verbose_name='Total Capacity'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Used Count'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total Price'),
        ),
    ]
