# Generated by Django 5.2.8 on 2026-04-07 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_review'),
        ('orders', '0003_coupon_total_capacity_coupon_used_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=15, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_ticket_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='events.ticketclass'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Value'),
        ),
    ]
