import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Locale = 'en' | 'fa' | 'ru' | 'tr'

export const localeMeta: Record<Locale, { label: string; shortLabel: string; nativeName: string; direction: 'ltr' | 'rtl'; intl: string }> = {
  en: { label: 'English', shortLabel: 'EN', nativeName: 'English', direction: 'ltr', intl: 'en-US' },
  fa: { label: 'فارسی', shortLabel: 'فا', nativeName: 'فارسی', direction: 'rtl', intl: 'fa-IR-u-ca-persian' },
  ru: { label: 'Русский', shortLabel: 'РУ', nativeName: 'Русский', direction: 'ltr', intl: 'ru-RU' },
  tr: { label: 'Türkçe', shortLabel: 'TR', nativeName: 'Türkçe', direction: 'ltr', intl: 'tr-TR' },
}

const copy = {
  en: {
    nav: { events: 'Events', music: 'Music', theater: 'Theater & Arts', sports: 'Sports', journal: 'Nexa Journal', search: 'Search artists, venues, or events', favorites: 'Saved events', account: 'My account', signIn: 'Sign in / Join', cart: 'Reservations' },
    footer: { discovery: 'Discover', allEvents: 'All events', withNexa: 'With Nexa', about: 'About us', contact: 'Contact', legal: 'Terms & privacy', newsletterTitle: 'A few good things, once a month', newsletterCopy: 'Curated culture and private drops, delivered with restraint.', subscribe: 'Subscribe', rights: '© 2026 Nexa. All rights reserved.', madeFor: 'Made for nights worth remembering' },
    common: { from: 'From', details: 'Details', reserve: 'Reserve tickets', viewAll: 'View all', event: 'event', events: 'events', home: 'Home', back: 'Back', loading: 'Loading…', learnMore: 'Learn more', explore: 'Explore events', seeAll: 'See all events', favorite: 'Save event', share: 'Share', selected: 'Selected', close: 'Close' },
    home: {
      kicker: 'Curated for life beyond the screen', titleLine1: 'Every night,', titleLine2: 'a new stage.', description: 'Nexa is where you find music, performance, and experiences that stay with you long after the lights go down.', browse: 'Browse events', weeklySelections: 'This week’s picks', proof: 'people have already found their next night out with Nexa.', editorialPick: 'Editor’s pick', reserveSeat: 'Reserve your seat', startsAt: 'Starting at', searchLabel: 'What are you looking for?', searchPlaceholder: 'Artist, show, or moment', cityLabel: 'Where?', anywhere: 'Anywhere in the city', quickPicks: 'Quick picks:', categoryEyebrow: 'Worlds to enter', categoryTitle: 'Choose the mood for tonight.', discoverShows: 'Explore shows', selectedEyebrow: 'Selected by Nexa', selectedTitle: 'Do not miss these this week.', viewCalendar: 'View calendar', cityPulse: 'The city pulse', cityTitle1: 'New York,', cityTitle2: 'through Nexa.', cityDescription: 'When the city has too many good options, we make the right ones easier to find — one memorable night at a time.', trustedEvents: 'trusted live events', securePayment: 'secure, transparent payments', cityEvents: 'Explore New York', clearTickets: 'Clear tickets', safeReservation: 'Safe reservation', support: 'Human support', clearTicketsText: 'Everything you need to know before you pay.', safeReservationText: 'Secure checkout and instant e-tickets.', supportText: 'A real person, every day of the week.', journalEyebrow: 'Beyond the ticket', journal: 'Nexa Journal', readMore: 'Read more', journalTitle: 'How to turn a concert into a night you remember.', journalSecond: 'Why live performance still feels like magic.', journalCategory: 'Experience guide', journalBackstage: 'Behind the curtain', quote: 'Nexa is not just a ticket. It is a good date with the city.', quoteBy: 'From the Nexa team', quoteRole: 'For unforgettable nights', newsletterEyebrow: 'Quietly, right on time', newsletterTitle1: 'When something good happens,', newsletterTitle2: 'you hear it first.', newsletterPlaceholder: 'your@email.com', newsletterNote: 'One cultural note a month. No noise.', newsletterButton: 'Join the list', cityVenue: 'Brooklyn Mirage', cityHighlight: 'The city after dark' },
    card: { ticketDetails: 'Ticket details', rating: 'rating', at: 'at', eventType: 'Live event' },
    cart: { title: 'Your reservations', selections: 'selections', emptyTitle: 'Make room for a new memory', emptyDescription: 'Find the event that moves you, then reserve it in a few thoughtful clicks.', discover: 'Discover events', payable: 'Total due', continue: 'Continue to secure checkout', note: 'Availability and final price are confirmed before payment.', remove: 'Remove' },
    listing: { eyebrow: 'Nexa calendar', title: 'Find your next night out.', description: 'Live music, theater, sport, and experiences — clearly presented, easy to reserve.', filters: 'Filters', reset: 'Reset all', category: 'Category', allCategories: 'All categories', time: 'Date', comingWeek: 'This week', weekend: 'This weekend', month: 'This month', anyDate: 'Any date', price: 'Price range', upTo: 'Up to', venue: 'Venue', allVenues: 'All venues', showEvents: 'Show {count} events', results: 'events to explore', searchPlaceholder: 'Search artists, shows, venues', search: 'Search', sorting: 'Sort:', soonest: 'Soonest', popular: 'Most popular', lowPrice: 'Lowest price', highPrice: 'Highest price', selectedTime: 'Selected date', noResultsTitle: 'Nothing matched that combination', noResultsDescription: 'Try a broader date, price range, or city.', clearFilters: 'Clear filters', loadMore: 'Show more events', connectionError: 'We could not reach the calendar', retry: 'Try again' },
    detail: { notFound: 'This event is no longer on the calendar', notFoundDescription: 'It may have ended, moved, or the link may have changed.', backToEvents: 'Back to events', venueDoors: 'Doors open 90 minutes before showtime', verifiedReviews: 'verified guest reviews', basedOn: 'Based on {count} reviews', bookingSecure: 'Nexa secure reservation', chooseTicket: 'Choose your tickets', stepZone: 'Choose a section', stepQuantity: 'Quantity', stepPayment: 'Checkout', chooseZone: '1. Select your preferred section', soldOut: 'This section is sold out', left: '{count} tickets left', ticketQuantity: '2. Ticket quantity', ticketTotal: 'Ticket total', continueBooking: 'Continue to checkout', capacityConfirmed: 'Capacity and price are rechecked before payment.', about: 'About this event', whatToKnow: 'Good to know', entryTiming: 'Entry and timing', cancellation: 'Cancellation & refunds', access: 'Getting there', reviews: 'Guest reviews', showReviews: 'Show all reviews', eventTime: 'Date & time', designedFor: 'Best for', designedForValue: 'Anyone who loves a live room', delivery: 'Ticket delivery', deliveryValue: 'Instantly in your Nexa account', related: 'More for your calendar', relatedTitle: 'You may also like', addToCart: 'Add to reservations', recent: 'New' },
    checkout: { emptyEyebrow: 'Your reservation bag is empty', emptyTitle: 'Choose something worth leaving home for.', emptyText: 'Find your next event. The rest takes only a few minutes.', successEyebrow: 'Reservation confirmed', successTitle: 'Your next great night is set.', successText: 'This is a demo confirmation. With the API connected, your e-ticket and payment details appear in your account immediately.', reference: 'Reference', account: 'View my reservations', backToExplore: 'Keep exploring', title: 'Secure checkout', subtitle: 'One thoughtful step away from your next live experience.', timer: 'Time held for your reservation', recipient: 'Guest details', recipientDescription: 'Your e-ticket and reservation details are linked to this information.', fullName: 'Full name', phone: 'Mobile number', email: 'Email', payment: 'Payment method', paymentDescription: 'Your payment is processed through a secure gateway.', online: 'Secure card payment', cards: 'Visa, Mastercard & supported cards', secure: 'Secure', pay: 'Pay {price}', preparing: 'Preparing secure payment…', terms: 'By continuing, you agree to Nexa’s terms and privacy policy.', summary: 'Reservation summary', item: 'item', coupon: 'Have a promo code?', apply: 'Apply', subtotal: 'Ticket subtotal', discount: 'Nexa discount', final: 'Total due', priceNote: 'Availability and final price are reconfirmed before payment.' },
    auth: { signIn: 'Sign in', join: 'Join Nexa', account: 'Account', backHome: 'Back to home' },
  },
  fa: {
    nav: { events: 'رویدادها', music: 'موسیقی', theater: 'تئاتر و هنر', sports: 'ورزش', journal: 'مجلهٔ نکسا', search: 'جست‌وجوی هنرمند، مکان یا رویداد', favorites: 'رویدادهای ذخیره‌شده', account: 'حساب من', signIn: 'ورود / عضویت', cart: 'رزروها' },
    footer: { discovery: 'کشف کنید', allEvents: 'همهٔ رویدادها', withNexa: 'همراه نکسا', about: 'دربارهٔ ما', contact: 'تماس با ما', legal: 'قوانین و حریم خصوصی', newsletterTitle: 'ماهی یک‌بار، چند اتفاق خوب', newsletterCopy: 'انتخاب‌های فرهنگی و دسترسی‌های ویژه، بی‌حاشیه در ایمیل شما.', subscribe: 'عضویت', rights: '© ۲۰۲۶ نکسا. همهٔ حقوق محفوظ است.', madeFor: 'برای شب‌هایی که ارزش به‌یادماندن دارند' },
    common: { from: 'از', details: 'جزئیات', reserve: 'رزرو بلیت', viewAll: 'نمایش همه', event: 'رویداد', events: 'رویداد', home: 'خانه', back: 'بازگشت', loading: 'در حال بارگذاری…', learnMore: 'بیشتر بدانید', explore: 'کشف رویدادها', seeAll: 'همهٔ رویدادها', favorite: 'ذخیرهٔ رویداد', share: 'اشتراک‌گذاری', selected: 'انتخاب‌شده', close: 'بستن' },
    home: { kicker: 'انتخاب‌شده برای زندگی بیرون از صفحه', titleLine1: 'هر شب،', titleLine2: 'یک صحنهٔ تازه.', description: 'نکسا جایی برای پیدا کردنِ موسیقی، نمایش و تجربه‌هایی است که مدت‌ها بعد از خاموش شدن نورها هم با شما می‌مانند.', browse: 'دیدن رویدادها', weeklySelections: 'انتخاب‌های این هفته', proof: 'نفر تا امروز شب بعدی‌شان را با نکسا پیدا کرده‌اند.', editorialPick: 'انتخاب تحریریه', reserveSeat: 'رزرو صندلی', startsAt: 'شروع از', searchLabel: 'دنبال چه اجرایی هستید؟', searchPlaceholder: 'هنرمند، اجرا یا اتفاق', cityLabel: 'کجا؟', anywhere: 'هر جای شهر', quickPicks: 'پیشنهاد سریع:', categoryEyebrow: 'جهانِ تجربه‌ها', categoryTitle: 'حالِ امشبت را انتخاب کن.', discoverShows: 'کشف اجراها', selectedEyebrow: 'به انتخاب نکسا', selectedTitle: 'این هفته، این‌ها را از دست نده.', viewCalendar: 'مشاهدهٔ تقویم', cityPulse: 'نبض شهر', cityTitle1: 'نیویورک،', cityTitle2: 'از نگاه نکسا.', cityDescription: 'وقتی شهر انتخاب‌های خوب زیادی دارد، ما پیدا کردنِ انتخاب درست را ساده‌تر می‌کنیم؛ هر بار برای یک شب به‌یادماندنی.', trustedEvents: 'رویداد زندهٔ معتبر', securePayment: 'پرداخت امن و روشن', cityEvents: 'رویدادهای نیویورک', clearTickets: 'بلیت، بی‌ابهام', safeReservation: 'رزرو مطمئن', support: 'یک نفر آن‌طرف خط هست', clearTicketsText: 'هرآنچه پیش از پرداخت باید بدانید.', safeReservationText: 'پرداخت امن و دریافت فوری بلیت دیجیتال.', supportText: 'پشتیبانی انسانی، هر روز هفته.', journalEyebrow: 'فراتر از بلیت', journal: 'مجلهٔ نکسا', readMore: 'بیشتر بخوانید', journalTitle: 'چطور از یک شب کنسرت، خاطره‌ای تمام‌قد بسازیم؟', journalSecond: 'چرا اجرای زنده هنوز جادویی است؟', journalCategory: 'راهنمای تجربه', journalBackstage: 'پشت صحنه', quote: 'نکسا فقط یک بلیت نیست؛ یک قرار خوب با شهر است.', quoteBy: 'از طرف تیم نکسا', quoteRole: 'برای شب‌های فراموش‌نشدنی', newsletterEyebrow: 'بی‌صدا، اما به‌موقع', newsletterTitle1: 'وقتی اتفاق خوبی افتاد،', newsletterTitle2: 'اول به شما می‌گوییم.', newsletterPlaceholder: 'your@email.com', newsletterNote: 'ماهی یک پیام فرهنگی؛ بدون شلوغ‌کاری.', newsletterButton: 'عضویت در خبرنامه', cityVenue: 'بروکلین میرِج', cityHighlight: 'شهر بعد از تاریکی' },
    card: { ticketDetails: 'جزئیات بلیت', rating: 'امتیاز', at: 'در', eventType: 'رویداد زنده' },
    cart: { title: 'سبد رزرو شما', selections: 'انتخاب', emptyTitle: 'جایی برای یک خاطرهٔ تازه باز کنید', emptyDescription: 'رویدادی را که دلتان را می‌برد پیدا کنید و با چند کلیکِ دقیق، رزرو را تمام کنید.', discover: 'کشف رویدادها', payable: 'مبلغ قابل پرداخت', continue: 'ادامه و تکمیل رزرو', note: 'قیمت و ظرفیت پیش از پرداخت دوباره بررسی می‌شود.', remove: 'حذف' },
    listing: { eyebrow: 'تقویم نکسا', title: 'دلیل بعدیِ بیرون رفتن را پیدا کن.', description: 'موسیقی زنده، نمایش، ورزش و تجربه‌های تازه؛ شفاف، حرفه‌ای و آمادهٔ رزرو.', filters: 'فیلترها', reset: 'حذف همه', category: 'دسته‌بندی', allCategories: 'همهٔ دسته‌ها', time: 'زمان', comingWeek: 'این هفته', weekend: 'آخر هفته', month: 'این ماه', anyDate: 'هر زمانی', price: 'محدودهٔ قیمت', upTo: 'تا', venue: 'مکان', allVenues: 'همهٔ مکان‌ها', showEvents: 'نمایش {count} رویداد', results: 'رویداد برای کشف کردن', searchPlaceholder: 'نام اجرا، هنرمند یا مکان', search: 'جست‌وجو', sorting: 'مرتب‌سازی:', soonest: 'نزدیک‌ترین زمان', popular: 'محبوب‌ترین', lowPrice: 'ارزان‌ترین', highPrice: 'گران‌ترین', selectedTime: 'زمان انتخاب‌شده', noResultsTitle: 'با این ترکیب چیزی پیدا نکردیم', noResultsDescription: 'فیلترها را کمی بازتر کنید یا انتخاب دیگری را امتحان کنید.', clearFilters: 'پاک کردن فیلترها', loadMore: 'نمایش رویدادهای بیشتر', connectionError: 'ارتباط با تقویم برقرار نشد', retry: 'تلاش دوباره' },
    detail: { notFound: 'این رویداد دیگر در تقویم نیست', notFoundDescription: 'شاید اجرا تمام شده، جابه‌جا شده یا لینک تغییر کرده باشد.', backToEvents: 'بازگشت به رویدادها', venueDoors: 'درهای سالن ۹۰ دقیقه پیش از اجرا باز می‌شوند', verifiedReviews: 'بازخورد خریداران تأییدشده', basedOn: 'بر پایهٔ {count} نظر', bookingSecure: 'رزرو امن نکسا', chooseTicket: 'بلیتت را انتخاب کن', stepZone: 'جایگاه', stepQuantity: 'تعداد', stepPayment: 'پرداخت', chooseZone: '۱. جایگاه دلخواهت را انتخاب کن', soldOut: 'ظرفیت این بخش تکمیل شده', left: '{count} بلیت باقی مانده', ticketQuantity: '۲. تعداد بلیت', ticketTotal: 'جمع بلیت‌ها', continueBooking: 'ادامهٔ رزرو و پرداخت', capacityConfirmed: 'قیمت و ظرفیت پیش از پرداخت نهایی دوباره تأیید می‌شود.', about: 'دربارهٔ اجرا', whatToKnow: 'اطلاعاتی که خوب است بدانید', entryTiming: 'شرایط ورود و زمان‌بندی', cancellation: 'کنسلی و بازگشت وجه', access: 'دسترسی به مکان برگزاری', reviews: 'نظرها', showReviews: 'نمایش همهٔ نظرها', eventTime: 'زمان اجرا', designedFor: 'مناسب برای', designedForValue: 'علاقه‌مندان به تجربه‌های زنده', delivery: 'دریافت بلیت', deliveryValue: 'بلافاصله در حساب نکسا', related: 'شاید دوست داشته باشید', relatedTitle: 'رویدادهای نزدیک به این انتخاب', addToCart: 'افزودن به سبد رزرو', recent: 'تازه' },
    checkout: { emptyEyebrow: 'سبد رزرو خالی است', emptyTitle: 'اول یک اتفاق خوب انتخاب کنید.', emptyText: 'رویداد دلخواهتان را پیدا کنید؛ بقیهٔ مسیر فقط چند دقیقه است.', successEyebrow: 'رزرو ثبت شد', successTitle: 'برای یک شب خوب آماده‌اید.', successText: 'این یک تأیید نمایشی است. با اتصال API، بلیت دیجیتال و جزئیات پرداخت بلافاصله در حساب شما قرار می‌گیرد.', reference: 'کد پیگیری', account: 'دیدن رزروهای من', backToExplore: 'ادامهٔ گشت‌وگذار', title: 'تکمیل رزرو', subtitle: 'فقط یک قدم تا تجربهٔ بعدی‌تان مانده است.', timer: 'زمان باقی‌مانده برای رزرو', recipient: 'اطلاعات دریافت‌کننده', recipientDescription: 'بلیت دیجیتال و جزئیات رزرو به این اطلاعات متصل می‌شود.', fullName: 'نام و نام خانوادگی', phone: 'شمارهٔ همراه', email: 'ایمیل', payment: 'روش پرداخت', paymentDescription: 'پرداخت شما با درگاه امن انجام می‌شود.', online: 'پرداخت امن آنلاین', cards: 'کارت‌های بانکی پشتیبانی‌شده', secure: 'امن', pay: 'پرداخت {price}', preparing: 'در حال آماده‌سازی پرداخت…', terms: 'با ادامه، قوانین و حریم خصوصی نکسا را می‌پذیرید.', summary: 'خلاصهٔ رزرو', item: 'مورد', coupon: 'کد تخفیف دارید؟', apply: 'اعمال', subtotal: 'جمع بلیت‌ها', discount: 'تخفیف نکسا', final: 'مبلغ قابل پرداخت', priceNote: 'قیمت و ظرفیت پیش از ورود به پرداخت دوباره تأیید می‌شود.' },
    auth: { signIn: 'ورود', join: 'ثبت‌نام', account: 'حساب من', backHome: 'بازگشت به خانه' },
  },
  ru: {
    nav: { events: 'События', music: 'Музыка', theater: 'Театр и искусство', sports: 'Спорт', journal: 'Журнал Nexa', search: 'Артист, площадка или событие', favorites: 'Сохранённые события', account: 'Мой аккаунт', signIn: 'Войти / Регистрация', cart: 'Бронирования' },
    footer: { discovery: 'Открывайте', allEvents: 'Все события', withNexa: 'С Nexa', about: 'О нас', contact: 'Контакты', legal: 'Условия и конфиденциальность', newsletterTitle: 'Несколько хороших вещей раз в месяц', newsletterCopy: 'Отобранная культура и закрытые анонсы — без лишнего шума.', subscribe: 'Подписаться', rights: '© 2026 Nexa. Все права защищены.', madeFor: 'Для ночей, которые хочется помнить' },
    common: { from: 'От', details: 'Подробнее', reserve: 'Забронировать', viewAll: 'Смотреть все', event: 'событие', events: 'событий', home: 'Главная', back: 'Назад', loading: 'Загрузка…', learnMore: 'Подробнее', explore: 'Открыть события', seeAll: 'Все события', favorite: 'Сохранить', share: 'Поделиться', selected: 'Выбрано', close: 'Закрыть' },
    home: { kicker: 'Для жизни за пределами экрана', titleLine1: 'Каждая ночь —', titleLine2: 'новая сцена.', description: 'Nexa помогает находить музыку, спектакли и впечатления, которые остаются с вами после финального света.', browse: 'Смотреть события', weeklySelections: 'Выбор недели', proof: 'человек уже нашли свой следующий вечер с Nexa.', editorialPick: 'Выбор редакции', reserveSeat: 'Забронировать место', startsAt: 'От', searchLabel: 'Что вы ищете?', searchPlaceholder: 'Артист, шоу или настроение', cityLabel: 'Где?', anywhere: 'В любом районе города', quickPicks: 'Быстрый выбор:', categoryEyebrow: 'Миры впечатлений', categoryTitle: 'Выберите настроение на сегодня.', discoverShows: 'Открыть события', selectedEyebrow: 'Выбор Nexa', selectedTitle: 'Не пропустите на этой неделе.', viewCalendar: 'Открыть календарь', cityPulse: 'Пульс города', cityTitle1: 'Нью-Йорк,', cityTitle2: 'вместе с Nexa.', cityDescription: 'Когда в городе слишком много отличных вариантов, мы помогаем найти ваш — для одного незабываемого вечера.', trustedEvents: 'проверенных событий', securePayment: 'безопасная прозрачная оплата', cityEvents: 'События Нью-Йорка', clearTickets: 'Понятные билеты', safeReservation: 'Надёжное бронирование', support: 'Поддержка людей', clearTicketsText: 'Вся важная информация до оплаты.', safeReservationText: 'Защищённая оплата и мгновенный e-ticket.', supportText: 'Реальный человек на связи каждый день.', journalEyebrow: 'Больше, чем билет', journal: 'Журнал Nexa', readMore: 'Читать больше', journalTitle: 'Как превратить концерт в вечер, который запомнится?', journalSecond: 'Почему живое выступление всё ещё похоже на магию?', journalCategory: 'Гид по впечатлениям', journalBackstage: 'За кулисами', quote: 'Nexa — не просто билет. Это хорошее свидание с городом.', quoteBy: 'Команда Nexa', quoteRole: 'Для незабываемых ночей', newsletterEyebrow: 'Тихо и вовремя', newsletterTitle1: 'Когда случается что-то хорошее,', newsletterTitle2: 'вы узнаёте первыми.', newsletterPlaceholder: 'your@email.com', newsletterNote: 'Одно культурное письмо в месяц. Без шума.', newsletterButton: 'Подписаться', cityVenue: 'Бруклин Мираж', cityHighlight: 'Город после заката' },
    card: { ticketDetails: 'О билетах', rating: 'рейтинг', at: 'в', eventType: 'Живое событие' },
    cart: { title: 'Ваши бронирования', selections: 'выбрано', emptyTitle: 'Освободите место для нового воспоминания', emptyDescription: 'Найдите событие, которое вас зацепит, и завершите бронирование за несколько спокойных шагов.', discover: 'Открыть события', payable: 'К оплате', continue: 'Перейти к оплате', note: 'Наличие и финальная цена подтверждаются перед оплатой.', remove: 'Удалить' },
    listing: { eyebrow: 'Календарь Nexa', title: 'Найдите следующий повод выйти.', description: 'Музыка, театр, спорт и новые впечатления — ясно, красиво, готово к бронированию.', filters: 'Фильтры', reset: 'Сбросить', category: 'Категория', allCategories: 'Все категории', time: 'Дата', comingWeek: 'На этой неделе', weekend: 'На выходных', month: 'В этом месяце', anyDate: 'Любая дата', price: 'Диапазон цен', upTo: 'До', venue: 'Площадка', allVenues: 'Все площадки', showEvents: 'Показать {count} событий', results: 'событий для открытия', searchPlaceholder: 'Артист, шоу или площадка', search: 'Поиск', sorting: 'Сортировка:', soonest: 'Ближайшие', popular: 'Популярные', lowPrice: 'Сначала дешевле', highPrice: 'Сначала дороже', selectedTime: 'Выбранная дата', noResultsTitle: 'По этому набору ничего не найдено', noResultsDescription: 'Попробуйте расширить дату, цену или город.', clearFilters: 'Очистить фильтры', loadMore: 'Показать ещё', connectionError: 'Не удалось загрузить календарь', retry: 'Повторить' },
    detail: { notFound: 'Этого события больше нет в календаре', notFoundDescription: 'Оно могло завершиться, переехать или ссылка могла измениться.', backToEvents: 'К событиям', venueDoors: 'Двери открываются за 90 минут до начала', verifiedReviews: 'отзывы проверенных гостей', basedOn: 'На основе {count} отзывов', bookingSecure: 'Безопасное бронирование Nexa', chooseTicket: 'Выберите билеты', stepZone: 'Секция', stepQuantity: 'Количество', stepPayment: 'Оплата', chooseZone: '1. Выберите секцию', soldOut: 'В этой секции нет мест', left: 'Осталось {count} билетов', ticketQuantity: '2. Количество билетов', ticketTotal: 'Итого за билеты', continueBooking: 'К безопасной оплате', capacityConfirmed: 'Наличие и цена перепроверяются перед оплатой.', about: 'О событии', whatToKnow: 'Полезно знать', entryTiming: 'Вход и время', cancellation: 'Отмена и возврат', access: 'Как добраться', reviews: 'Отзывы гостей', showReviews: 'Все отзывы', eventTime: 'Дата и время', designedFor: 'Кому подойдёт', designedForValue: 'Тем, кто любит живые впечатления', delivery: 'Получение билета', deliveryValue: 'Сразу в вашем аккаунте Nexa', related: 'Для вашего календаря', relatedTitle: 'Вам также может понравиться', addToCart: 'Добавить к бронированиям', recent: 'Новое' },
    checkout: { emptyEyebrow: 'Корзина бронирования пуста', emptyTitle: 'Выберите то, ради чего стоит выйти из дома.', emptyText: 'Найдите следующее событие. Остальное займёт всего несколько минут.', successEyebrow: 'Бронирование подтверждено', successTitle: 'Ваш отличный вечер уже запланирован.', successText: 'Это демо-подтверждение. При подключённом API e-ticket и детали оплаты сразу появятся в вашем аккаунте.', reference: 'Номер бронирования', account: 'Мои бронирования', backToExplore: 'Продолжить поиск', title: 'Безопасная оплата', subtitle: 'До следующего живого впечатления — один спокойный шаг.', timer: 'Время удержания бронирования', recipient: 'Данные гостя', recipientDescription: 'Электронный билет и детали бронирования привязаны к этим данным.', fullName: 'Полное имя', phone: 'Номер телефона', email: 'Email', payment: 'Способ оплаты', paymentDescription: 'Платёж обрабатывается через защищённый шлюз.', online: 'Безопасная оплата картой', cards: 'Visa, Mastercard и поддерживаемые карты', secure: 'Защищено', pay: 'Оплатить {price}', preparing: 'Готовим безопасную оплату…', terms: 'Продолжая, вы принимаете условия и политику Nexa.', summary: 'Итог бронирования', item: 'позиция', coupon: 'Есть промокод?', apply: 'Применить', subtotal: 'Сумма билетов', discount: 'Скидка Nexa', final: 'К оплате', priceNote: 'Наличие и финальная цена подтверждаются перед оплатой.' },
    auth: { signIn: 'Войти', join: 'Регистрация', account: 'Мой аккаунт', backHome: 'На главную' },
  },
  tr: {
    nav: { events: 'Etkinlikler', music: 'Müzik', theater: 'Tiyatro ve Sanat', sports: 'Spor', journal: 'Nexa Dergi', search: 'Sanatçı, mekân veya etkinlik ara', favorites: 'Kaydedilenler', account: 'Hesabım', signIn: 'Giriş / Katıl', cart: 'Rezervasyonlar' },
    footer: { discovery: 'Keşfet', allEvents: 'Tüm etkinlikler', withNexa: 'Nexa ile', about: 'Hakkımızda', contact: 'İletişim', legal: 'Koşullar ve gizlilik', newsletterTitle: 'Ayda bir, birkaç güzel şey', newsletterCopy: 'Özenle seçilmiş kültür ve özel duyurular, gereksiz gürültü olmadan.', subscribe: 'Abone ol', rights: '© 2026 Nexa. Tüm hakları saklıdır.', madeFor: 'Hatırlamaya değer geceler için' },
    common: { from: 'Başlangıç', details: 'Detaylar', reserve: 'Bilet seç', viewAll: 'Tümünü gör', event: 'etkinlik', events: 'etkinlik', home: 'Ana sayfa', back: 'Geri', loading: 'Yükleniyor…', learnMore: 'Daha fazlası', explore: 'Etkinlikleri keşfet', seeAll: 'Tüm etkinlikler', favorite: 'Kaydet', share: 'Paylaş', selected: 'Seçildi', close: 'Kapat' },
    home: { kicker: 'Ekranın ötesindeki hayat için seçildi', titleLine1: 'Her gece,', titleLine2: 'yeni bir sahne.', description: 'Nexa; ışıklar kapandıktan sonra bile sizinle kalan müzikleri, gösterileri ve deneyimleri bulduğunuz yer.', browse: 'Etkinlikleri keşfet', weeklySelections: 'Bu haftanın seçkisi', proof: 'kişi Nexa ile bir sonraki gece planını buldu.', editorialPick: 'Editör seçimi', reserveSeat: 'Yerini ayır', startsAt: 'Başlangıç', searchLabel: 'Ne arıyorsunuz?', searchPlaceholder: 'Sanatçı, gösteri veya an', cityLabel: 'Nerede?', anywhere: 'Şehrin her yerinde', quickPicks: 'Hızlı seçim:', categoryEyebrow: 'Deneyim dünyaları', categoryTitle: 'Bu gecenin ruh hâlini seçin.', discoverShows: 'Gösterileri keşfet', selectedEyebrow: 'Nexa seçkisi', selectedTitle: 'Bu hafta bunları kaçırmayın.', viewCalendar: 'Takvimi gör', cityPulse: 'Şehrin nabzı', cityTitle1: 'New York,', cityTitle2: 'Nexa ile.', cityDescription: 'Şehirde çok fazla iyi seçenek olduğunda, doğru olanı bulmayı kolaylaştırıyoruz — unutulmaz bir gece için.', trustedEvents: 'güvenilir canlı etkinlik', securePayment: 'güvenli ve şeffaf ödeme', cityEvents: 'New York etkinlikleri', clearTickets: 'Net biletler', safeReservation: 'Güvenli rezervasyon', support: 'İnsan desteği', clearTicketsText: 'Ödemeden önce ihtiyacınız olan her şey.', safeReservationText: 'Güvenli ödeme ve anında e-bilet.', supportText: 'Her gün gerçek bir insan yanınızda.', journalEyebrow: 'Biletten fazlası', journal: 'Nexa Dergi', readMore: 'Devamını oku', journalTitle: 'Bir konseri unutulmaz bir geceye nasıl dönüştürürsünüz?', journalSecond: 'Canlı performans neden hâlâ sihir gibi hissettiriyor?', journalCategory: 'Deneyim rehberi', journalBackstage: 'Perde arkası', quote: 'Nexa sadece bir bilet değil. Şehirle güzel bir buluşma.', quoteBy: 'Nexa ekibi', quoteRole: 'Unutulmaz geceler için', newsletterEyebrow: 'Sessizce, tam zamanında', newsletterTitle1: 'İyi bir şey olduğunda,', newsletterTitle2: 'ilk siz duyun.', newsletterPlaceholder: 'your@email.com', newsletterNote: 'Ayda bir kültür notu. Gürültüsüz.', newsletterButton: 'Listeye katıl', cityVenue: 'Brooklyn Mirage', cityHighlight: 'Karanlıktan sonra şehir' },
    card: { ticketDetails: 'Bilet detayları', rating: 'puan', at: '—', eventType: 'Canlı etkinlik' },
    cart: { title: 'Rezervasyonlarınız', selections: 'seçim', emptyTitle: 'Yeni bir anı için yer açın', emptyDescription: 'Sizi hareket ettiren etkinliği bulun, ardından birkaç sakin adımda rezervasyonu tamamlayın.', discover: 'Etkinlikleri keşfet', payable: 'Toplam ödeme', continue: 'Güvenli ödemeye devam et', note: 'Müsaitlik ve son fiyat ödeme öncesinde onaylanır.', remove: 'Kaldır' },
    listing: { eyebrow: 'Nexa takvimi', title: 'Dışarı çıkmak için yeni bir neden bulun.', description: 'Canlı müzik, tiyatro, spor ve yeni deneyimler — net, şık ve rezerve etmeye hazır.', filters: 'Filtreler', reset: 'Sıfırla', category: 'Kategori', allCategories: 'Tüm kategoriler', time: 'Tarih', comingWeek: 'Bu hafta', weekend: 'Bu hafta sonu', month: 'Bu ay', anyDate: 'Herhangi bir tarih', price: 'Fiyat aralığı', upTo: 'En fazla', venue: 'Mekân', allVenues: 'Tüm mekânlar', showEvents: '{count} etkinliği göster', results: 'keşfedilecek etkinlik', searchPlaceholder: 'Sanatçı, gösteri veya mekân ara', search: 'Ara', sorting: 'Sırala:', soonest: 'En yakın', popular: 'En popüler', lowPrice: 'En düşük fiyat', highPrice: 'En yüksek fiyat', selectedTime: 'Seçili tarih', noResultsTitle: 'Bu kombinasyona uygun sonuç yok', noResultsDescription: 'Daha geniş bir tarih, fiyat veya şehir deneyin.', clearFilters: 'Filtreleri temizle', loadMore: 'Daha fazla etkinlik', connectionError: 'Takvime ulaşılamadı', retry: 'Tekrar dene' },
    detail: { notFound: 'Bu etkinlik artık takvimde değil', notFoundDescription: 'Etkinlik bitmiş, taşınmış veya bağlantı değişmiş olabilir.', backToEvents: 'Etkinliklere dön', venueDoors: 'Kapılar gösteriden 90 dakika önce açılır', verifiedReviews: 'doğrulanmış konuk yorumları', basedOn: '{count} yoruma göre', bookingSecure: 'Nexa güvenli rezervasyon', chooseTicket: 'Biletinizi seçin', stepZone: 'Bölüm', stepQuantity: 'Adet', stepPayment: 'Ödeme', chooseZone: '1. Tercih ettiğiniz bölümü seçin', soldOut: 'Bu bölüm tükendi', left: '{count} bilet kaldı', ticketQuantity: '2. Bilet adedi', ticketTotal: 'Bilet toplamı', continueBooking: 'Güvenli ödemeye devam et', capacityConfirmed: 'Müsaitlik ve fiyat ödeme öncesinde tekrar kontrol edilir.', about: 'Etkinlik hakkında', whatToKnow: 'Bilmeniz gerekenler', entryTiming: 'Giriş ve zamanlama', cancellation: 'İptal ve iade', access: 'Ulaşım', reviews: 'Konuk yorumları', showReviews: 'Tüm yorumları gör', eventTime: 'Tarih ve saat', designedFor: 'Kimler için', designedForValue: 'Canlı deneyimleri sevenler için', delivery: 'Bilet teslimi', deliveryValue: 'Nexa hesabınızda anında', related: 'Takviminiz için daha fazlası', relatedTitle: 'Bunları da sevebilirsiniz', addToCart: 'Rezervasyonlara ekle', recent: 'Yeni' },
    checkout: { emptyEyebrow: 'Rezervasyon çantanız boş', emptyTitle: 'Evden çıkmaya değecek bir şey seçin.', emptyText: 'Bir sonraki etkinliğinizi bulun. Geri kalanı yalnızca birkaç dakika sürer.', successEyebrow: 'Rezervasyon onaylandı', successTitle: 'Harika geceniz hazır.', successText: 'Bu bir demo onayıdır. API bağlandığında e-biletiniz ve ödeme detaylarınız hesabınızda hemen görünür.', reference: 'Referans', account: 'Rezervasyonlarımı gör', backToExplore: 'Keşfe devam et', title: 'Güvenli ödeme', subtitle: 'Bir sonraki canlı deneyiminize yalnızca bir sakin adım kaldı.', timer: 'Rezervasyon için kalan süre', recipient: 'Misafir bilgileri', recipientDescription: 'E-biletiniz ve rezervasyon detaylarınız bu bilgilere bağlanır.', fullName: 'Ad soyad', phone: 'Cep telefonu', email: 'E-posta', payment: 'Ödeme yöntemi', paymentDescription: 'Ödemeniz güvenli bir ağ geçidi üzerinden işlenir.', online: 'Güvenli kart ödemesi', cards: 'Visa, Mastercard ve desteklenen kartlar', secure: 'Güvenli', pay: '{price} öde', preparing: 'Güvenli ödeme hazırlanıyor…', terms: 'Devam ederek Nexa koşullarını ve gizlilik politikasını kabul edersiniz.', summary: 'Rezervasyon özeti', item: 'öğe', coupon: 'Promosyon kodunuz var mı?', apply: 'Uygula', subtotal: 'Bilet ara toplamı', discount: 'Nexa indirimi', final: 'Toplam ödeme', priceNote: 'Müsaitlik ve son fiyat ödeme öncesinde tekrar onaylanır.' },
    auth: { signIn: 'Giriş', join: 'Nexa’ya katıl', account: 'Hesabım', backHome: 'Ana sayfaya dön' },
  },
} as const

type Copy = typeof copy.en

const valueAt = (source: object, key: string): string | undefined =>
  key.split('.').reduce<unknown>((value, part) => (value && typeof value === 'object' ? (value as Record<string, unknown>)[part] : undefined), source) as string | undefined

type LanguageContextValue = {
  locale: Locale
  direction: 'ltr' | 'rtl'
  setLocale: (locale: Locale) => void
  t: (key: string, replacements?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [locale, setLocale] = useState<Locale>(() => {
    const saved = localStorage.getItem('nexa-locale') as Locale | null
    return saved && saved in localeMeta ? saved : 'en'
  })

  useEffect(() => {
    const meta = localeMeta[locale]
    document.documentElement.lang = locale
    document.documentElement.dir = meta.direction
    localStorage.setItem('nexa-locale', locale)
  }, [locale])

  const value = useMemo<LanguageContextValue>(() => ({
    locale,
    direction: localeMeta[locale].direction,
    setLocale,
    t: (key, replacements) => {
      const template = valueAt(copy[locale], key) ?? valueAt(copy.en, key) ?? key
      return Object.entries(replacements ?? {}).reduce((result, [name, replacement]) => result.replaceAll(`{${name}}`, String(replacement)), template)
    },
  }), [locale])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider.')
  return context
}

export const getIntlLocale = (locale: Locale) => localeMeta[locale].intl
export type TranslationCopy = Copy
